---
abstract: 'run smoke tests for your distribution'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.70
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Joseki-Command-smoke
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Config: 0
  Cwd: 0
  Dist::Joseki: 0
  Template: 0
  Test::TAP::HTMLMatrix: 0
  YAML: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Joseki-Command-smoke
  homepage: http://search.cpan.org/dist/Dist-Joseki-Command-smoke/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hanekomu/dist-joseki-command-smoke.git
version: 0.01
